// src/lib/bloomberg-codes.ts
// Bloomberg topic codes — static master list
// Do not edit manually — update from Bloomberg when codes change

export interface BloombergCode {
  code: string
  description: string
  category: string
}

export const BLOOMBERG_CODES: BloombergCode[] = [
  // Agencies, Government
  { code: 'GOV', description: 'Government News', category: 'Agencies, Government' },
  { code: 'MAS', description: 'Singapore Monetary Authority', category: 'Agencies, Government' },
  { code: 'MOF', description: 'Ministry of Finance, Japan', category: 'Agencies, Government' },
  { code: 'RBA', description: 'Reserve Bank of Australia', category: 'Agencies, Government' },
  { code: 'RBI', description: 'Reserve Bank of India', category: 'Agencies, Government' },
  { code: 'RBNZ', description: 'Reserve Bank of New Zealand', category: 'Agencies, Government' },
  { code: 'WB', description: 'World Bank', category: 'Agencies, Government' },

  // Bonds, Government
  { code: 'ASB', description: 'Asia Bonds', category: 'Bonds, Government' },
  { code: 'AUB', description: 'Australian Bonds', category: 'Bonds, Government' },
  { code: 'AXB', description: 'Asia Bonds Excl. Japan', category: 'Bonds, Government' },
  { code: 'EMD', description: 'Emerging Market Debt', category: 'Bonds, Government' },
  { code: 'JPB', description: 'Japan Bonds', category: 'Bonds, Government' },
  { code: 'NEWBON', description: 'New Bonds', category: 'Bonds, Government' },
  { code: 'YBN', description: 'Yankee Bonds', category: 'Bonds, Government' },

  // Chemicals
  { code: 'AGCH', description: 'Agricultural Chemicals', category: 'Chemicals' },
  { code: 'PLASTICS', description: 'Plastics', category: 'Chemicals' },
  { code: 'SPCH', description: 'Specialty Chemicals', category: 'Chemicals' },

  // Commodities, non Energy
  { code: 'MET', description: 'Metals', category: 'Commodities, non Energy' },
  { code: 'MNG', description: 'Mining', category: 'Commodities, non Energy' },
  { code: 'NONFERR', description: 'Non-Ferrous Metals', category: 'Commodities, non Energy' },

  // Corporates
  { code: 'BON', description: 'Bond Market News', category: 'Corporates' },
  { code: 'CNI', description: 'Corporate Bonds - New Issues', category: 'Corporates' },
  { code: 'COR', description: 'Corporate Bonds', category: 'Corporates' },
  { code: 'CORPFIN', description: 'Corporate Finance', category: 'Corporates' },
  { code: 'EBN', description: 'Eurobond Markets', category: 'Corporates' },
  { code: 'RED', description: 'Corporate Bond Redemptions', category: 'Corporates' },
  { code: 'SAMURAI', description: 'Samurai Bonds', category: 'Corporates' },

  // Currencies
  { code: 'BITCOIN', description: 'Bitcoin', category: 'Currencies' },
  { code: 'DIGITALCUR', description: 'Digital, Cryptocurrencies', category: 'Currencies' },
  { code: 'FRX', description: 'Forex, Currencies', category: 'Currencies' },
  { code: 'FRXDIGITAL', description: 'Crypto, Digital Assets', category: 'Currencies' },
  { code: 'FXKEY', description: 'FX Key News', category: 'Currencies' },
  { code: 'FXVOICE', description: 'FX Comments', category: 'Currencies' },

  // Economies
  { code: 'ECO', description: 'Economic News', category: 'Economies' },
  { code: 'HKECO', description: 'Hong Kong Economy', category: 'Economies' },
  { code: 'IDECO', description: 'Indonesia Economy', category: 'Economies' },
  { code: 'JNECO', description: 'Japan Economy', category: 'Economies' },
  { code: 'MECO', description: 'Malaysia Economy', category: 'Economies' },
  { code: 'PHECO', description: 'Philippine Economy', category: 'Economies' },
  { code: 'SECO', description: 'Singapore Economy', category: 'Economies' },
  { code: 'TAECO', description: 'Taiwan Economy', category: 'Economies' },
  { code: 'THECO', description: 'Thailand Economy', category: 'Economies' },

  // Energy
  { code: 'ALTNRG', description: 'Alternative Energy', category: 'Energy' },
  { code: 'FIELD', description: 'Oil & Gas Fields', category: 'Energy' },
  { code: 'GAS', description: 'Natural Gas', category: 'Energy' },
  { code: 'LNG', description: 'Liquefied Natural Gas', category: 'Energy' },
  { code: 'LPG', description: 'Liquefied Petroleum Gas', category: 'Energy' },
  { code: 'NRG', description: 'Energy', category: 'Energy' },
  { code: 'SOLAR', description: 'Solar Energy', category: 'Energy' },

  // Equity
  { code: 'ASX', description: 'Australian Stock Exchange', category: 'Equity' },
  { code: 'AUS', description: 'Australian Stock Market', category: 'Equity' },
  { code: 'CHS', description: 'Chinese Stock Market', category: 'Equity' },
  { code: 'EUREX', description: 'Eurex Deutschland', category: 'Equity' },
  { code: 'EURONEXT', description: 'Euronext', category: 'Equity' },
  { code: 'FPS', description: 'French Stock Market', category: 'Equity' },
  { code: 'GRS', description: 'German Stock Market', category: 'Equity' },
  { code: 'HKS', description: 'Hong Kong, Chinese Stocks', category: 'Equity' },
  { code: 'IDS', description: 'Indian Stock Market', category: 'Equity' },
  { code: 'IJS', description: 'Indonesian Stock Market', category: 'Equity' },
  { code: 'IMS', description: 'Italian Stock Market', category: 'Equity' },
  { code: 'JASDAQ', description: 'Jasdaq', category: 'Equity' },
  { code: 'JPS', description: 'Japanese Stock Market', category: 'Equity' },
  { code: 'LNS', description: 'London Stock Exchange', category: 'Equity' },
  { code: 'MKS', description: 'Malaysia Stocks', category: 'Equity' },
  { code: 'NAS', description: 'Netherlands Stocks', category: 'Equity' },
  { code: 'NASDAQ', description: 'Nasdaq Stock Market', category: 'Equity' },
  { code: 'NYSE', description: 'New York Stock Exchange', category: 'Equity' },
  { code: 'OFEX', description: 'OFEX (UK OTC Market)', category: 'Equity' },
  { code: 'OSE', description: 'Osaka Stock Exchange', category: 'Equity' },
  { code: 'PMS', description: 'Philippine Stocks', category: 'Equity' },
  { code: 'SES', description: 'Singapore Stock Exchange', category: 'Equity' },
  { code: 'SGX', description: 'Singapore Exchange', category: 'Equity' },
  { code: 'SPS', description: 'Singapore Stocks', category: 'Equity' },
  { code: 'STK', description: 'Stock Market News', category: 'Equity' },
  { code: 'SWX', description: 'Swiss Stock Exchange', category: 'Equity' },
  { code: 'TBS', description: 'Thailand Stocks', category: 'Equity' },
  { code: 'TSE', description: 'Tokyo Stock Exchange', category: 'Equity' },
  { code: 'TTS', description: 'Taiwan Stocks', category: 'Equity' },
  { code: 'USS', description: 'US Stocks', category: 'Equity' },

  // Financial News
  { code: 'ADR', description: 'American Depositary Receipts', category: 'Financial News' },
  { code: 'ADVISE', description: 'Advisers Investment', category: 'Financial News' },
  { code: 'ALLFND', description: 'All Funds', category: 'Financial News' },
  { code: 'BBK', description: 'Buybacks', category: 'Financial News' },
  { code: 'BLK', description: 'Block Trades', category: 'Financial News' },
  { code: 'CORPGOV', description: 'Corporate Governance', category: 'Financial News' },
  { code: 'CSR', description: 'CSR', category: 'Financial News' },
  { code: 'DIV', description: 'Dividends', category: 'Financial News' },
  { code: 'ERN', description: 'Earnings', category: 'Financial News' },
  { code: 'ESG', description: 'Environmental Social Governance', category: 'Financial News' },
  { code: 'EST', description: 'Earnings Estimates', category: 'Financial News' },
  { code: 'ETF', description: 'Exchange Traded Funds', category: 'Financial News' },
  { code: 'EXC', description: 'Exchange News', category: 'Financial News' },
  { code: 'FAMILYOFF', description: 'Family Office, Wealth Management', category: 'Financial News' },
  { code: 'FCP', description: 'Financial Commercial Paper', category: 'Financial News' },
  { code: 'FDI', description: 'Foreign Direct Investment', category: 'Financial News' },
  { code: 'FILINGS', description: 'Filings Company', category: 'Financial News' },
  { code: 'FIMR', description: 'Fixed-Income Market Reports', category: 'Financial News' },
  { code: 'FINHIRE', description: 'Financial Hiring', category: 'Financial News' },
  { code: 'FINTECH', description: 'Financial Technology', category: 'Financial News' },
  { code: 'FND', description: 'Funds, Mutual Trusts', category: 'Financial News' },
  { code: 'GDR', description: 'Global Depositary Receipt', category: 'Financial News' },
  { code: 'HEDGE', description: 'Hedge Funds', category: 'Financial News' },
  { code: 'HR', description: 'Human Resources', category: 'Financial News' },
  { code: 'ICO', description: 'Initial Coin Offering', category: 'Financial News' },
  { code: 'IPO', description: 'Initial Public Offerings', category: 'Financial News' },
  { code: 'JHEAD', description: 'Japan Headlines', category: 'Financial News' },
  { code: 'LBO', description: 'Buyout, Private Equity', category: 'Financial News' },
  { code: 'LOANS', description: 'Loans & Financing', category: 'Financial News' },
  { code: 'MNA', description: 'Mergers & Acquisitions', category: 'Financial News' },
  { code: 'ORDER', description: 'Orders & Contracts', category: 'Financial News' },
  { code: 'PE', description: 'Private Equity', category: 'Financial News' },
  { code: 'PRIVBANK', description: 'Private Banking', category: 'Financial News' },
  { code: 'PVT', description: 'Private Placements', category: 'Financial News' },
  { code: 'PZN', description: 'Privatization', category: 'Financial News' },
  { code: 'RGT', description: 'Rights Issue', category: 'Financial News' },
  { code: 'RLS', description: 'Press Releases', category: 'Financial News' },
  { code: 'SMALLCAP', description: 'Small-Cap Stock Research', category: 'Financial News' },
  { code: 'STARTUPS', description: 'StartUps', category: 'Financial News' },
  { code: 'TNM', description: 'Shareholdings', category: 'Financial News' },
  { code: 'VC', description: 'Venture Capital', category: 'Financial News' },
  { code: 'VNT', description: 'Ventures & JVs', category: 'Financial News' },
  { code: 'WARN', description: 'Warnings Profit', category: 'Financial News' },

  // General News
  { code: 'ART', description: 'Fine Art', category: 'General News' },
  { code: 'COS', description: 'Companies', category: 'General News' },
  { code: 'CURTAIN', description: 'Arts Previews', category: 'General News' },
  { code: 'EDU', description: 'Education', category: 'General News' },
  { code: 'FINANCE', description: 'Financials', category: 'General News' },
  { code: 'GEN', description: 'General News', category: 'General News' },
  { code: 'MUSIC', description: 'Music Industry', category: 'General News' },
  { code: 'RLG', description: 'Religion', category: 'General News' },
  { code: 'SCIENCE', description: 'Science', category: 'General News' },
  { code: 'SPACE', description: 'Space Exploration', category: 'General News' },
  { code: 'TRAVEL', description: 'Travel', category: 'General News' },

  // Geographic
  { code: 'AFRICA', description: 'Africa', category: 'Geographic' },
  { code: 'AME', description: 'Africa, Mideast', category: 'Geographic' },
  { code: 'ASIA', description: 'Asia, Pacific Rim', category: 'Geographic' },
  { code: 'ASIAX', description: 'Asia ex. Japan, Australia', category: 'Geographic' },
  { code: 'AU', description: 'Australia', category: 'Geographic' },
  { code: 'BEIJING', description: 'Beijing', category: 'Geographic' },
  { code: 'BRAZIL', description: 'Brazil', category: 'Geographic' },
  { code: 'CA', description: 'Canada', category: 'Geographic' },
  { code: 'CENAM', description: 'Central America', category: 'Geographic' },
  { code: 'CHICAGO', description: 'Chicago', category: 'Geographic' },
  { code: 'CHINA', description: 'China', category: 'Geographic' },
  { code: 'DUBAI', description: 'Dubai', category: 'Geographic' },
  { code: 'EEU', description: 'Eastern Europe', category: 'Geographic' },
  { code: 'EM', description: 'Emerging Markets', category: 'Geographic' },
  { code: 'ESTONIA', description: 'Estonia', category: 'Geographic' },
  { code: 'EUROPE', description: 'Europe', category: 'Geographic' },
  { code: 'FR', description: 'France', category: 'Geographic' },
  { code: 'HK', description: 'Hong Kong', category: 'Geographic' },
  { code: 'INDIA', description: 'India', category: 'Geographic' },
  { code: 'INDO', description: 'Indonesia', category: 'Geographic' },
  { code: 'ISRAEL', description: 'Israel', category: 'Geographic' },
  { code: 'JAPAN', description: 'Japan', category: 'Geographic' },
  { code: 'KAZAKH', description: 'Kazakhstan', category: 'Geographic' },
  { code: 'KOREA', description: 'Korea, North and South', category: 'Geographic' },
  { code: 'LATAM', description: 'Latin America', category: 'Geographic' },
  { code: 'LITHUANIA', description: 'Lithuania', category: 'Geographic' },
  { code: 'MACAU', description: 'Macau', category: 'Geographic' },
  { code: 'MALAY', description: 'Malaysia', category: 'Geographic' },
  { code: 'MALTA', description: 'Malta', category: 'Geographic' },
  { code: 'MENA', description: 'Middle East', category: 'Geographic' },
  { code: 'MYANMAR', description: 'Myanmar', category: 'Geographic' },
  { code: 'NASIA', description: 'North Asia', category: 'Geographic' },
  { code: 'NIGERIA', description: 'Nigeria', category: 'Geographic' },
  { code: 'PACIFIC', description: 'Pacific Islands', category: 'Geographic' },
  { code: 'PAK', description: 'Pakistan', category: 'Geographic' },
  { code: 'PHIL', description: 'Philippines', category: 'Geographic' },
  { code: 'RUSSIA', description: 'Russia', category: 'Geographic' },
  { code: 'SEASIA', description: 'South East Asia', category: 'Geographic' },
  { code: 'SHANGHAI', description: 'Shanghai', category: 'Geographic' },
  { code: 'SOUTHAM', description: 'South America', category: 'Geographic' },
  { code: 'SP', description: 'Singapore', category: 'Geographic' },
  { code: 'STKITTS', description: 'St Kitts and Nevis', category: 'Geographic' },
  { code: 'TALLINN', description: 'Tallinn', category: 'Geographic' },
  { code: 'THAI', description: 'Thailand', category: 'Geographic' },
  { code: 'TORONTO', description: 'Toronto', category: 'Geographic' },
  { code: 'TWN', description: 'Taiwan', category: 'Geographic' },
  { code: 'UAE', description: 'United Arab Emirates', category: 'Geographic' },
  { code: 'UK', description: 'United Kingdom', category: 'Geographic' },
  { code: 'US', description: 'United States', category: 'Geographic' },
  { code: 'VIET', description: 'Vietnam', category: 'Geographic' },
  { code: 'VILNIUS', description: 'Vilnius', category: 'Geographic' },

  // Industries
  { code: 'ACC', description: 'Accounting', category: 'Industries' },
  { code: 'ADV', description: 'Advertising', category: 'Industries' },
  { code: 'AGR', description: 'Agriculture', category: 'Industries' },
  { code: 'AI', description: 'Artificial Intelligence', category: 'Industries' },
  { code: 'AIR', description: 'Airlines', category: 'Industries' },
  { code: 'ARO', description: 'Aerospace & Defense', category: 'Industries' },
  { code: 'ASFT', description: 'Application Software', category: 'Industries' },
  { code: 'AUP', description: 'Automotive Parts', category: 'Industries' },
  { code: 'AUT', description: 'Automobiles', category: 'Industries' },
  { code: 'BIGDATA', description: 'Big Data', category: 'Industries' },
  { code: 'BLOCKCHAIN', description: 'Blockchain Technology', category: 'Industries' },
  { code: 'BNK', description: 'Banking', category: 'Industries' },
  { code: 'BTC', description: 'Biotechnology', category: 'Industries' },
  { code: 'BVG', description: 'Beverages', category: 'Industries' },
  { code: 'CARD', description: 'Credit Cards, Charge Cards', category: 'Industries' },
  { code: 'CHM', description: 'Chemicals', category: 'Industries' },
  { code: 'CLNTRIAL', description: 'Clinical Trials', category: 'Industries' },
  { code: 'CLO', description: 'Clothing', category: 'Industries' },
  { code: 'CLOUD', description: 'Cloud Computing', category: 'Industries' },
  { code: 'CNO', description: 'Casinos, Gaming', category: 'Industries' },
  { code: 'CONS', description: 'Consumer Goods, Retail', category: 'Industries' },
  { code: 'CPR', description: 'Computers', category: 'Industries' },
  { code: 'CRE', description: 'Commercial Real Estate', category: 'Industries' },
  { code: 'CRYPTOMKT', description: 'Crypto Markets', category: 'Industries' },
  { code: 'CST', description: 'Construction & Engineering', category: 'Industries' },
  { code: 'DRG', description: 'Drugs, Pharmaceuticals', category: 'Industries' },
  { code: 'ECOM', description: 'E-commerce', category: 'Industries' },
  { code: 'ELE', description: 'Electronics', category: 'Industries' },
  { code: 'ELQ', description: 'Electrical Equipment', category: 'Industries' },
  { code: 'ENV', description: 'Environment, Waste Management', category: 'Industries' },
  { code: 'FCELL', description: 'Fuel Cells', category: 'Industries' },
  { code: 'FILM', description: 'Film, Cinema', category: 'Industries' },
  { code: 'FIN', description: 'Financial Services', category: 'Industries' },
  { code: 'FOD', description: 'Food', category: 'Industries' },
  { code: 'GAMES', description: 'Games, Video & Computer', category: 'Industries' },
  { code: 'GYM', description: 'Sporting Goods', category: 'Industries' },
  { code: 'HDWR', description: 'Hardware & Storage', category: 'Industries' },
  { code: 'HEA', description: 'Health Care', category: 'Industries' },
  { code: 'HMF', description: 'Furnishings, Appliances', category: 'Industries' },
  { code: 'HOU', description: 'Consumer Products', category: 'Industries' },
  { code: 'INS', description: 'Insurance', category: 'Industries' },
  { code: 'INTERNET', description: 'Internet', category: 'Industries' },
  { code: 'IOT', description: 'Internet of Things', category: 'Industries' },
  { code: 'ITSECURE', description: 'IT Security', category: 'Industries' },
  { code: 'LEI', description: 'Leisure', category: 'Industries' },
  { code: 'LOD', description: 'Lodging', category: 'Industries' },
  { code: 'MAC', description: 'Machinery, Manufacturing', category: 'Industries' },
  { code: 'MAR', description: 'Marine Transport', category: 'Industries' },
  { code: 'MARKETING', description: 'Marketing', category: 'Industries' },
  { code: 'MDS', description: 'Medical Supplies', category: 'Industries' },
  { code: 'MED', description: 'Media', category: 'Industries' },
  { code: 'MEDICAL', description: 'Medical, Health Research', category: 'Industries' },
  { code: 'MOBILE', description: 'Mobile Phones, Apps', category: 'Industries' },
  { code: 'MTC', description: 'Medical Technology', category: 'Industries' },
  { code: 'NANO', description: 'Nanotechnology', category: 'Industries' },
  { code: 'NET', description: 'Networking, Computers', category: 'Industries' },
  { code: 'NFT', description: 'Non-Fungible Tokens', category: 'Industries' },
  { code: 'NUK', description: 'Nuclear Power', category: 'Industries' },
  { code: 'OIL', description: 'Oil', category: 'Industries' },
  { code: 'PLUGINEV', description: 'EVs', category: 'Industries' },
  { code: 'PUBLICREL', description: 'Public Relations', category: 'Industries' },
  { code: 'RADIO', description: 'Radio', category: 'Industries' },
  { code: 'RAI', description: 'Railroads', category: 'Industries' },
  { code: 'REIT', description: 'REITs', category: 'Industries' },
  { code: 'RET', description: 'Retailing', category: 'Industries' },
  { code: 'SCR', description: 'Securities Firms', category: 'Industries' },
  { code: 'SEM', description: 'Semiconductors', category: 'Industries' },
  { code: 'SEQ', description: 'Semiconductor Equipment', category: 'Industries' },
  { code: 'SHIP', description: 'Shipping', category: 'Industries' },
  { code: 'SHOW', description: 'Shows, Trade & Expositions', category: 'Industries' },
  { code: 'SHP', description: 'Shipbuilders', category: 'Industries' },
  { code: 'SOCIALNET', description: 'Social Networking', category: 'Industries' },
  { code: 'SOF', description: 'Software & Computer Apps', category: 'Industries' },
  { code: 'STL', description: 'Steel', category: 'Industries' },
  { code: 'SUSTAIN', description: 'Sustainability', category: 'Industries' },
  { code: 'SVC', description: 'Commercial Services', category: 'Industries' },
  { code: 'TEC', description: 'Technology', category: 'Industries' },
  { code: 'TEL', description: 'Telecom Equipment', category: 'Industries' },
  { code: 'TEX', description: 'Textiles', category: 'Industries' },
  { code: 'TLS', description: 'Telecom Services', category: 'Industries' },
  { code: 'TMT', description: 'Communications', category: 'Industries' },
  { code: 'TOB', description: 'Tobacco', category: 'Industries' },
  { code: 'TOY', description: 'Toys', category: 'Industries' },
  { code: 'TRD', description: 'Trade', category: 'Industries' },
  { code: 'TRN', description: 'Transportation', category: 'Industries' },
  { code: 'TVNEWS', description: 'TV Industry News', category: 'Industries' },
  { code: 'UTI', description: 'Utilities', category: 'Industries' },
  { code: 'VIDEO', description: 'Video Industry News', category: 'Industries' },
  { code: 'VIRTUALR', description: 'Virtual, Augmented Reality', category: 'Industries' },
  { code: 'WRLS', description: 'Wireless Communications', category: 'Industries' },

  // Japanese
  { code: 'CALAP', description: 'Calendar, Asia-Pac (Japanese)', category: 'Japanese' },
  { code: 'CALE', description: 'Calendars, Europe (Japanese)', category: 'Japanese' },
  { code: 'JBANK', description: 'Japan Banking', category: 'Japanese' },
  { code: 'JBHY', description: 'New Bond Sales (Japanese)', category: 'Japanese' },
  { code: 'JBMR', description: 'Japan Bond Market Report', category: 'Japanese' },
  { code: 'JBOJ', description: 'Bank of Japan (Japanese)', category: 'Japanese' },
  { code: 'JCAL', description: 'Japanese Calendars', category: 'Japanese' },
  { code: 'JCEN', description: 'Central Banks (Japanese)', category: 'Japanese' },
  { code: 'JER', description: 'Japan Earnings', category: 'Japanese' },
  { code: 'JFCO', description: 'Foreign Companies (Japanese)', category: 'Japanese' },
  { code: 'JFSA', description: 'Japan Financial Services Agency', category: 'Japanese' },
  { code: 'JFUND', description: 'Japanese Fund Prospectuses', category: 'Japanese' },
  { code: 'JGOV', description: 'Japanese Government', category: 'Japanese' },
  { code: 'JIPO', description: 'Japanese Prospectuses', category: 'Japanese' },
  { code: 'JMETI', description: 'Japanese METI', category: 'Japanese' },
  { code: 'JSO', description: 'General News (Japanese)', category: 'Japanese' },
  { code: 'JSUM', description: 'Media Summaries (Japanese)', category: 'Japanese' },
  { code: 'KAISETU', description: 'Kaisetu (Japanese)', category: 'Japanese' },
  { code: 'KIGYO', description: 'Company News (Japanese)', category: 'Japanese' },
  { code: 'METI', description: 'METI Japan', category: 'Japanese' },
  { code: 'MOTHERS', description: 'Mothers (Kanji)', category: 'Japanese' },
  { code: 'TANSHIN', description: 'Japanese Tanshin Reports', category: 'Japanese' },
  { code: 'YENWATCH', description: 'Yen Watch', category: 'Japanese' },
  { code: 'YUHO', description: 'Japanese Company Filings', category: 'Japanese' },

  // Legal
  { code: 'LAW', description: 'Legal Affairs, Litigation', category: 'Legal' },
  { code: 'LAWVIEWS', description: 'Legal Expert Analysis', category: 'Legal' },
  { code: 'LAWYERCHG', description: 'Law Firm Actions', category: 'Legal' },
  { code: 'PATENT', description: 'Patents, Intellectual Property', category: 'Legal' },

  // Money Markets
  { code: 'BOJ', description: 'Bank of Japan', category: 'Money Markets' },
  { code: 'CBC', description: 'Taiwan Central Bank', category: 'Money Markets' },
  { code: 'FRN', description: 'Floating Rate Notes', category: 'Money Markets' },
  { code: 'MMK', description: 'Money Markets', category: 'Money Markets' },

  // Sports
  { code: 'FORMULA1', description: 'Formula One', category: 'Sports' },
  { code: 'OLY', description: 'Olympics', category: 'Sports' },
  { code: 'SPORTBIZ', description: 'Sports Business', category: 'Sports' },
  { code: 'SPORTS', description: 'Sports', category: 'Sports' },
]

// All unique categories for grouping in the UI
export const BLOOMBERG_CATEGORIES = [...new Set(BLOOMBERG_CODES.map(c => c.category))]

// Search helper — searches code and description, case-insensitive
export function searchBloombergCodes(query: string): BloombergCode[] {
  if (!query.trim()) return BLOOMBERG_CODES
  const q = query.toLowerCase()
  return BLOOMBERG_CODES.filter(
    c =>
      c.code.toLowerCase().includes(q) ||
      c.description.toLowerCase().includes(q) ||
      c.category.toLowerCase().includes(q)
  )
}
