import { ALL_SEED_ARTICLES } from '../lib/press-releases/mock'
import type { CompanyFull } from '../types/company.types'

export const SEED_COMPANY: CompanyFull = {
  id: 82,
  name_en: 'Mitsubishi Heavy Industries, Ltd.',
  name_zh_hans: '三菱重工业股份有限公司',
  name_zh_hant: '三菱重工業股份有限公司',
  name_ja: '三菱重工業株式会社',
  name_ko: null,
  status: 'active',
  logo_article_url: null,
  logo_top_url: null,
  url: 'https://www.mhi.com',
  url_ja: 'https://www.mhi.com/jp',
  blog: null,
  facebook: null,
  twitter: 'https://twitter.com/MHI_Group',
  youtube: 'https://www.youtube.com/user/MitsubishiHeavyInd',
  linkedin: 'https://www.linkedin.com/company/mitsubishi-heavy-industries',
  telegram: null,
  instagram: null,
  established: '1884',
  exchange_listed_date: '1949-05-16',
  employees: '80,000+',
  duns_number: '690552828',
  otc: 'MHVIY',
  market_id: null,
  address_street: '3-1, Marunouchi 3-chome',
  address_district: 'Chiyoda-ku',
  address_city: 'Tokyo',
  address_country: 'Japan',
  telephone: '+81-3-6716-3111',
  facsimile: '+81-3-6716-5800',
  company_email: null,
  key_person_1_name: 'Seiji Izumisawa',
  key_person_1_title: 'President & CEO',
  key_person_2_name: 'Hisato Kozawa',
  key_person_2_title: 'Executive Vice President',
  about_html: '<p>Mitsubishi Heavy Industries (MHI) Group is one of the world\'s leading industrial groups, spanning energy, smart infrastructure, industrial machinery, aerospace and defense. MHI Group combines cutting-edge technology with deep experience to deliver innovative, integrated solutions that help to realize a carbon neutral world, improve the quality of life and ensure a safer world. For more information, please visit <a href="https://www.mhi.com">www.mhi.com</a> or follow our insights and stories on <a href="https://spectra.mhi.com">spectra.mhi.com</a>.</p>',
  about_prosemirror: null,
  languages: ['EN'],
  secondary_languages: ['JA'],
  created_at: '2019-03-12T00:00:00Z',
  updated_at: '2026-05-18T21:47:33Z',
  created_by: 1,
  updated_by: 3,
  updated_by_name: 'Krischan Balasbas',
  annual_report_url: null,
  annual_report_name: 'MHI_AR2026.pdf',
  annual_report_date: '2026-03-31',
  annual_report_size: '4.2 MB',
  portal_username: 'mhi.jp.123',
  portal_password: '••••••••••••',

  contacts: [
    {
      id: 1,
      company_id: 82,
      name: 'Kengo Tatsukawa',
      position: 'Communications & PR',
      email: 'kengo_tatsukawa@mhi.co.jp',
      phone: '+81-3-6716-2168',
      fax: null,
      contact_type: 'freetext',
      email_format: 'html',
      notes: null,
      sort_order: 0,
      created_at: '2019-03-12T00:00:00Z',
      updated_at: '2019-03-12T00:00:00Z',
    },
    {
      id: 2,
      company_id: 82,
      name: 'Kenichi Nakamura',
      position: null,
      email: 'kenichi_nakamura@mhi.co.jp',
      phone: '+81-3-6716-2168',
      fax: null,
      contact_type: 'freetext',
      email_format: 'html',
      notes: null,
      sort_order: 1,
      created_at: '2019-03-12T00:00:00Z',
      updated_at: '2019-03-12T00:00:00Z',
    },
    {
      id: 3,
      company_id: 82,
      name: 'Kazuyo Takeda',
      position: null,
      email: 'kazuyo.takeda@jcnnewswire.com',
      phone: null,
      fax: null,
      contact_type: 'freetext',
      email_format: 'html',
      notes: 'JCN Newswire liaison contact',
      sort_order: 2,
      created_at: '2020-01-15T00:00:00Z',
      updated_at: '2020-01-15T00:00:00Z',
    },
  ],

  sectors: [
    { id: 1, company_id: 82, sector_id: 211, sector_type: 'Industry',     sector_name: 'Aerospace & Defence' },
    { id: 2, company_id: 82, sector_id: 232, sector_type: 'Environment',  sector_name: 'Alternative Energy' },
    { id: 3, company_id: 82, sector_id: 33,  sector_type: 'Industry',     sector_name: 'Construct, Engineering' },
    { id: 4, company_id: 82, sector_id: 43,  sector_type: 'Environment',  sector_name: 'Energy, Alternatives' },
    { id: 5, company_id: 82, sector_id: 30,  sector_type: 'Technology',   sector_name: 'Engineering' },
    { id: 6, company_id: 82, sector_id: 245, sector_type: 'Environment',  sector_name: 'EVs, Transportation' },
    { id: 7, company_id: 82, sector_id: 247, sector_type: 'Environment',  sector_name: 'Smart Cities' },
  ],

  exchange_listings: [
    {
      id: 1,
      company_id: 82,
      exchange_id: 'XTKS',
      exchange_name: 'Tokyo Stock Exchange',
      ticker_code: '7011',
      isin: 'JP3900000005',
      sedol: '6597672',
      cusip: null,
      created_at: '2019-03-12T00:00:00Z',
      updated_at: '2019-03-12T00:00:00Z',
    },
    {
      id: 2,
      company_id: 82,
      exchange_id: 'OOTC',
      exchange_name: 'OTC US',
      ticker_code: 'MHVIY',
      isin: 'US6068221042',
      sedol: 'B04MYG7',
      cusip: '606822104',
      created_at: '2019-03-12T00:00:00Z',
      updated_at: '2019-03-12T00:00:00Z',
    },
    {
      id: 3,
      company_id: 82,
      exchange_id: 'OOTC',
      exchange_name: 'OTC US',
      ticker_code: 'MHVYF',
      isin: 'US6068221042',
      sedol: 'B04MYG7',
      cusip: '606822104',
      created_at: '2019-03-12T00:00:00Z',
      updated_at: '2019-03-12T00:00:00Z',
    },
    {
      id: 4,
      company_id: 82,
      exchange_id: 'XFRA',
      exchange_name: 'Frankfurt Stock Exchange',
      ticker_code: 'MIH',
      isin: 'DE000A0D9PT0',
      sedol: 'B04MYG7',
      cusip: null,
      created_at: '2019-03-12T00:00:00Z',
      updated_at: '2019-03-12T00:00:00Z',
    },
  ],

  wire_codes: [
    { id: 1,  company_id: 82, wire_code_id: 101, wire_code: { id: 101, source: 'reuters',   code_type: 'Geographic',        code: 'ASIA',  name: 'Asia' } },
    { id: 2,  company_id: 82, wire_code_id: 102, wire_code: { id: 102, source: 'reuters',   code_type: 'Industrial Sector', code: 'ENQ',   name: 'Energy Equipment' } },
    { id: 3,  company_id: 82, wire_code_id: 103, wire_code: { id: 103, source: 'reuters',   code_type: 'Industrial Sector', code: 'IND',   name: 'Industrial Equipment' } },
    { id: 4,  company_id: 82, wire_code_id: 104, wire_code: { id: 104, source: 'reuters',   code_type: 'Geographic',        code: 'JP',    name: 'Japan' } },
    { id: 5,  company_id: 82, wire_code_id: 105, wire_code: { id: 105, source: 'reuters',   code_type: 'Industrial Sector', code: 'MAC',   name: 'Metal Goods and Engineering' } },
    { id: 6,  company_id: 82, wire_code_id: 106, wire_code: { id: 106, source: 'reuters',   code_type: 'General News',      code: 'NEWR',  name: 'News Releases' } },
    { id: 7,  company_id: 82, wire_code_id: 201, wire_code: { id: 201, source: 'bloomberg', code_type: 'Geographic',        code: 'ASIA',  name: 'Asia, Pacific Rim' } },
    { id: 8,  company_id: 82, wire_code_id: 202, wire_code: { id: 202, source: 'bloomberg', code_type: 'Company',           code: 'COS',   name: 'Companies' } },
    { id: 9,  company_id: 82, wire_code_id: 203, wire_code: { id: 203, source: 'bloomberg', code_type: 'Industrial Sector', code: 'CST',   name: 'Construction & Engineering' } },
    { id: 10, company_id: 82, wire_code_id: 204, wire_code: { id: 204, source: 'bloomberg', code_type: 'Industrial Sector', code: 'NRG',   name: 'Energy' } },
    { id: 11, company_id: 82, wire_code_id: 205, wire_code: { id: 205, source: 'bloomberg', code_type: 'Geographic',        code: 'JAPAN', name: 'Japan' } },
    { id: 12, company_id: 82, wire_code_id: 206, wire_code: { id: 206, source: 'bloomberg', code_type: 'Geographic',        code: 'JPS',   name: 'Japanese Stock Market' } },
    { id: 13, company_id: 82, wire_code_id: 207, wire_code: { id: 207, source: 'bloomberg', code_type: 'Industrial Sector', code: 'MAC',   name: 'Machinery, Manufacturing' } },
  ],

  rss_feeds: [
    {
      id: 1,
      company_id: 82,
      feed_name: 'ACN Newswire - Asia',
      url: 'https://www.acnnewswire.com/rss/sector/211',
      sector_id: 211,
      sector_name: 'Aerospace & Defence',
      status: 'active',
      created_at: '2019-03-12T00:00:00Z',
      updated_at: '2019-03-12T00:00:00Z',
    },
    {
      id: 2,
      company_id: 82,
      feed_name: 'ACN Newswire - Japan',
      url: 'https://www.acnnewswire.com/rss/sector/30',
      sector_id: 30,
      sector_name: 'Engineering',
      status: 'active',
      created_at: '2019-03-12T00:00:00Z',
      updated_at: '2019-03-12T00:00:00Z',
    },
    {
      id: 3,
      company_id: 82,
      feed_name: 'ACN Newswire - Marine',
      url: 'https://www.acnnewswire.com/rss/sector/185',
      sector_id: 185,
      sector_name: 'Marine & Offshore',
      status: 'paused',
      created_at: '2019-03-12T00:00:00Z',
      updated_at: '2019-03-12T00:00:00Z',
    },
  ],

  wire_services: [
    { id: 1, company_id: 82, name: 'Delilah Lin',                       email: 'News@EnergyTrend.com',         country: 'Taiwan' },
    { id: 2, company_id: 82, name: 'editorial@energystmedia.com',       email: 'editorial@energystmedia.com',  country: 'UK' },
    { id: 3, company_id: 82, name: 'Ian Stuart',                        email: 'istuart@nacleanenergy.com',    country: 'USA' },
    { id: 4, company_id: 82, name: 'Mikaila Adams',                     email: 'madams@endeavorb2b.com',       country: 'USA' },
    { id: 5, company_id: 82, name: 'Nikkan Kogyo editor',               email: 'newsrelease@po.nikkan.co.jp',  country: 'Japan' },
    { id: 6, company_id: 82, name: 'Editor Rita Brown',                 email: 'editor@energyvoice.com',       country: 'UK' },
  ],

  relations: [],

  delivery_settings: {
    allow_access: true,
    show_photos: true,
    show_banner: false,
    company_will_mail: false,
    show_extended_boilerplate: false,
    show_archives: true,
    show_alerts: true,
    delivery_method: 'standard',
  },
}

export const TOYOTA: CompanyFull = {
  id: 91,
  name_en: 'Toyota Motor Corporation',
  name_zh_hans: '丰田汽车公司',
  name_zh_hant: '豐田汽車公司',
  name_ja: 'トヨタ自動車株式会社',
  name_ko: '도요타 자동차',
  status: 'active',
  logo_article_url: null,
  logo_top_url: null,
  url: 'https://www.toyota-global.com',
  url_ja: 'https://www.toyota.co.jp',
  blog: null,
  facebook: 'https://www.facebook.com/toyota',
  twitter: 'https://twitter.com/Toyota',
  youtube: 'https://www.youtube.com/toyota',
  linkedin: 'https://www.linkedin.com/company/toyota-motor-corporation',
  telegram: null,
  instagram: 'https://www.instagram.com/toyota',
  established: '1937',
  exchange_listed_date: '1949-05-16',
  employees: '370,000+',
  duns_number: '692811911',
  otc: 'TM',
  market_id: null,
  address_street: '1 Toyota-cho',
  address_district: 'Toyota City',
  address_city: 'Aichi Prefecture',
  address_country: 'Japan',
  telephone: '+81-565-28-2121',
  facsimile: null,
  company_email: null,
  key_person_1_name: 'Koji Sato',
  key_person_1_title: 'President & CEO',
  key_person_2_name: 'Akio Toyoda',
  key_person_2_title: 'Chairman',
  about_html: '<p>Toyota Motor Corporation is a Japanese multinational automotive manufacturer headquartered in Toyota City, Aichi, Japan. It is one of the largest automobile manufacturers in the world by production volume.</p>',
  about_prosemirror: null,
  languages: ['EN'],
  secondary_languages: ['JA', 'ZH-HANS', 'ZH-HANT', 'KO'],
  created_at: '2018-06-01T00:00:00Z',
  updated_at: '2026-04-10T09:22:00Z',
  created_by: 1,
  updated_by: 2,
  updated_by_name: 'Shirley Chang',
  annual_report_url: null,
  annual_report_name: 'Toyota_AR2026.pdf',
  annual_report_date: '2026-03-31',
  annual_report_size: '6.1 MB',
  portal_username: 'toyota.jp.001',
  portal_password: '••••••••••••',
  contacts: [
    { id: 10, company_id: 91, name: 'Haruto Watanabe', position: 'Global PR Manager', email: 'h.watanabe@toyota.co.jp', phone: '+81-565-28-2000', fax: null, contact_type: 'freetext', email_format: 'html', notes: null, sort_order: 0, created_at: '2018-06-01T00:00:00Z', updated_at: '2018-06-01T00:00:00Z' },
  ],
  sectors: [
    { id: 20, company_id: 91, sector_id: 123, sector_type: 'Industry',     sector_name: 'Automotive' },
    { id: 21, company_id: 91, sector_id: 245, sector_type: 'Environment',  sector_name: 'EVs, Transportation' },
    { id: 22, company_id: 91, sector_id: 91,  sector_type: 'Industry',     sector_name: 'Manufacturing' },
  ],
  exchange_listings: [
    { id: 10, company_id: 91, exchange_id: 'XTKS', exchange_name: 'Tokyo Stock Exchange', ticker_code: '7203', isin: 'JP3633400001', sedol: '6900643', cusip: null, created_at: '2018-06-01T00:00:00Z', updated_at: '2018-06-01T00:00:00Z' },
    { id: 11, company_id: 91, exchange_id: 'XNYS', exchange_name: 'NYSE',                 ticker_code: 'TM',   isin: 'US8923313071', sedol: '2890537', cusip: '892331307', created_at: '2018-06-01T00:00:00Z', updated_at: '2018-06-01T00:00:00Z' },
  ],
  wire_codes: [
    { id: 20, company_id: 91, wire_code_id: 101, wire_code: { id: 101, source: 'reuters',   code_type: 'Geographic',        code: 'ASIA',  name: 'Asia' } },
    { id: 21, company_id: 91, wire_code_id: 104, wire_code: { id: 104, source: 'reuters',   code_type: 'Geographic',        code: 'JP',    name: 'Japan' } },
    { id: 22, company_id: 91, wire_code_id: 108, wire_code: { id: 108, source: 'reuters',   code_type: 'Industrial Sector', code: 'AUT',   name: 'Automobiles, Equipment' } },
    { id: 23, company_id: 91, wire_code_id: 201, wire_code: { id: 201, source: 'bloomberg', code_type: 'Geographic',        code: 'ASIA',  name: 'Asia, Pacific Rim' } },
    { id: 24, company_id: 91, wire_code_id: 205, wire_code: { id: 205, source: 'bloomberg', code_type: 'Geographic',        code: 'JAPAN', name: 'Japan' } },
    { id: 25, company_id: 91, wire_code_id: 208, wire_code: { id: 208, source: 'bloomberg', code_type: 'Industrial Sector', code: 'AUTO',  name: 'Automotive' } },
  ],
  rss_feeds: [],
  wire_services: [],
  relations: [
    { id: 1, company_id: 91, related_company_id: 82, related_company_name: 'Mitsubishi Heavy Industries, Ltd.', relation_type: 'sister' },
  ],
  delivery_settings: {
    allow_access: true,
    show_photos: true,
    show_banner: false,
    company_will_mail: false,
    show_extended_boilerplate: false,
    show_archives: true,
    show_alerts: true,
    delivery_method: 'standard',
  },
}

export const FUJITSU: CompanyFull = {
  id: 103,
  name_en: 'Fujitsu Limited',
  name_zh_hans: '富士通株式会社',
  name_zh_hant: '富士通株式會社',
  name_ja: '富士通株式会社',
  name_ko: null,
  status: 'active',
  logo_article_url: null,
  logo_top_url: null,
  url: 'https://www.fujitsu.com',
  url_ja: 'https://www.fujitsu.com/jp',
  blog: null,
  facebook: null,
  twitter: 'https://twitter.com/Fujitsu_Global',
  youtube: 'https://www.youtube.com/fujitsu',
  linkedin: 'https://www.linkedin.com/company/fujitsu',
  telegram: null,
  instagram: null,
  established: '1935',
  exchange_listed_date: '1949-05-16',
  employees: '124,000+',
  duns_number: null,
  otc: null,
  market_id: null,
  address_street: 'Shiodome City Center, 1-5-2 Higashi-Shimbashi',
  address_district: 'Minato-ku',
  address_city: 'Tokyo',
  address_country: 'Japan',
  telephone: '+81-3-6252-2220',
  facsimile: null,
  company_email: null,
  key_person_1_name: 'Takahito Tokita',
  key_person_1_title: 'President & CEO',
  key_person_2_name: null,
  key_person_2_title: null,
  about_html: '<p>Fujitsu is a leading Japanese information and communication technology company. Through the use of technology, Fujitsu aspires to help customers focus on growth and innovation in the face of uncertainty and change.</p>',
  about_prosemirror: null,
  languages: ['EN'],
  secondary_languages: ['JA', 'ZH-HANS'],
  created_at: '2019-01-10T00:00:00Z',
  updated_at: '2026-03-15T11:00:00Z',
  created_by: 1,
  updated_by: 1,
  updated_by_name: 'Bruce Porter',
  annual_report_url: null,
  annual_report_name: 'Fujitsu_AR2026.pdf',
  annual_report_date: '2026-03-31',
  annual_report_size: '5.4 MB',
  portal_username: 'fujitsu.jp.001',
  portal_password: '••••••••••••',
  contacts: [
    { id: 20, company_id: 103, name: 'Yoko Miyashita', position: 'Corporate Communications', email: 'pr@fujitsu.com', phone: '+81-3-6252-2220', fax: null, contact_type: 'freetext', email_format: 'html', notes: null, sort_order: 0, created_at: '2019-01-10T00:00:00Z', updated_at: '2019-01-10T00:00:00Z' },
  ],
  sectors: [
    { id: 30, company_id: 103, sector_id: 190, sector_type: 'Technology', sector_name: 'Enterprise IT' },
    { id: 31, company_id: 103, sector_id: 239, sector_type: 'Technology', sector_name: 'Digitalization' },
    { id: 32, company_id: 103, sector_id: 261, sector_type: 'Technology', sector_name: 'Artificial Intel [AI]' },
    { id: 33, company_id: 103, sector_id: 30,  sector_type: 'Industry',   sector_name: 'Engineering' },
  ],
  exchange_listings: [
    { id: 20, company_id: 103, exchange_id: 'XTKS', exchange_name: 'Tokyo Stock Exchange', ticker_code: '6702', isin: 'JP3818000006', sedol: '6345063', cusip: null, created_at: '2019-01-10T00:00:00Z', updated_at: '2019-01-10T00:00:00Z' },
  ],
  wire_codes: [
    { id: 30, company_id: 103, wire_code_id: 101, wire_code: { id: 101, source: 'reuters',   code_type: 'Geographic',        code: 'ASIA',  name: 'Asia' } },
    { id: 31, company_id: 103, wire_code_id: 104, wire_code: { id: 104, source: 'reuters',   code_type: 'Geographic',        code: 'JP',    name: 'Japan' } },
    { id: 32, company_id: 103, wire_code_id: 109, wire_code: { id: 109, source: 'reuters',   code_type: 'Industrial Sector', code: 'DPR',   name: 'Data Processing, Office Equipment' } },
    { id: 33, company_id: 103, wire_code_id: 201, wire_code: { id: 201, source: 'bloomberg', code_type: 'Geographic',        code: 'ASIA',  name: 'Asia, Pacific Rim' } },
    { id: 34, company_id: 103, wire_code_id: 205, wire_code: { id: 205, source: 'bloomberg', code_type: 'Geographic',        code: 'JAPAN', name: 'Japan' } },
    { id: 35, company_id: 103, wire_code_id: 209, wire_code: { id: 209, source: 'bloomberg', code_type: 'Industrial Sector', code: 'TECH',  name: 'Technology' } },
  ],
  rss_feeds: [],
  wire_services: [],
  relations: [],
  delivery_settings: {
    allow_access: true,
    show_photos: true,
    show_banner: false,
    company_will_mail: false,
    show_extended_boilerplate: false,
    show_archives: true,
    show_alerts: true,
    delivery_method: 'standard',
  },
}

export const HONDA: CompanyFull = {
  id: 117,
  name_en: 'Honda Motor Co., Ltd.',
  name_zh_hans: '本田技研工业株式会社',
  name_zh_hant: '本田技研工業株式會社',
  name_ja: '本田技研工業株式会社',
  name_ko: null,
  status: 'active',
  logo_article_url: null,
  logo_top_url: null,
  url: 'https://www.honda.com',
  url_ja: 'https://www.honda.co.jp',
  blog: null,
  facebook: 'https://www.facebook.com/Honda',
  twitter: 'https://twitter.com/Honda',
  youtube: 'https://www.youtube.com/honda',
  linkedin: 'https://www.linkedin.com/company/honda-motor-co-ltd-',
  telegram: null,
  instagram: 'https://www.instagram.com/honda',
  established: '1948',
  exchange_listed_date: '1957-01-01',
  employees: '197,000+',
  duns_number: null,
  otc: null,
  market_id: null,
  address_street: '2-1-1 Minami-Aoyama',
  address_district: 'Minato-ku',
  address_city: 'Tokyo',
  address_country: 'Japan',
  telephone: '+81-3-3423-1111',
  facsimile: null,
  company_email: null,
  key_person_1_name: 'Toshihiro Mibe',
  key_person_1_title: 'President & CEO',
  key_person_2_name: null,
  key_person_2_title: null,
  about_html: '<p>Honda Motor Co., Ltd. is a multinational conglomerate manufacturer of automobiles, motorcycles, and power equipment, headquartered in Minato, Tokyo. Honda is the world\'s largest motorcycle manufacturer and one of the leading automakers.</p>',
  about_prosemirror: null,
  languages: ['EN'],
  secondary_languages: ['JA', 'ZH-HANS', 'ZH-HANT'],
  created_at: '2018-03-20T00:00:00Z',
  updated_at: '2026-04-22T08:00:00Z',
  created_by: 1,
  updated_by: 2,
  updated_by_name: 'Shirley Chang',
  annual_report_url: null,
  annual_report_name: 'Honda_AR2026.pdf',
  annual_report_date: '2026-03-31',
  annual_report_size: '4.7 MB',
  portal_username: 'honda.jp.001',
  portal_password: '••••••••••••',
  contacts: [
    { id: 30, company_id: 117, name: 'Keiichi Nakamura', position: 'Global Communications', email: 'keiichi.nakamura@honda.co.jp', phone: '+81-3-3423-1111', fax: null, contact_type: 'freetext', email_format: 'html', notes: null, sort_order: 0, created_at: '2018-03-20T00:00:00Z', updated_at: '2018-03-20T00:00:00Z' },
  ],
  sectors: [
    { id: 40, company_id: 117, sector_id: 123, sector_type: 'Industry',    sector_name: 'Automotive' },
    { id: 41, company_id: 117, sector_id: 91,  sector_type: 'Industry',    sector_name: 'Manufacturing' },
    { id: 42, company_id: 117, sector_id: 245, sector_type: 'Environment', sector_name: 'EVs, Transportation' },
  ],
  exchange_listings: [
    { id: 30, company_id: 117, exchange_id: 'XTKS', exchange_name: 'Tokyo Stock Exchange', ticker_code: '7267', isin: 'JP3854600008', sedol: '6436578', cusip: null,        created_at: '2018-03-20T00:00:00Z', updated_at: '2018-03-20T00:00:00Z' },
    { id: 31, company_id: 117, exchange_id: 'XNYS', exchange_name: 'NYSE',                 ticker_code: 'HMC',  isin: 'US4361061082', sedol: '2421922', cusip: '436106108', created_at: '2018-03-20T00:00:00Z', updated_at: '2018-03-20T00:00:00Z' },
  ],
  wire_codes: [
    { id: 40, company_id: 117, wire_code_id: 101, wire_code: { id: 101, source: 'reuters',   code_type: 'Geographic',        code: 'ASIA',  name: 'Asia' } },
    { id: 41, company_id: 117, wire_code_id: 104, wire_code: { id: 104, source: 'reuters',   code_type: 'Geographic',        code: 'JP',    name: 'Japan' } },
    { id: 42, company_id: 117, wire_code_id: 108, wire_code: { id: 108, source: 'reuters',   code_type: 'Industrial Sector', code: 'AUT',   name: 'Automobiles, Equipment' } },
    { id: 43, company_id: 117, wire_code_id: 201, wire_code: { id: 201, source: 'bloomberg', code_type: 'Geographic',        code: 'ASIA',  name: 'Asia, Pacific Rim' } },
    { id: 44, company_id: 117, wire_code_id: 205, wire_code: { id: 205, source: 'bloomberg', code_type: 'Geographic',        code: 'JAPAN', name: 'Japan' } },
    { id: 45, company_id: 117, wire_code_id: 208, wire_code: { id: 208, source: 'bloomberg', code_type: 'Industrial Sector', code: 'AUTO',  name: 'Automotive' } },
    { id: 46, company_id: 117, wire_code_id: 210, wire_code: { id: 210, source: 'bloomberg', code_type: 'Industrial Sector', code: 'TRAN',  name: 'Transportation' } },
  ],
  rss_feeds: [],
  wire_services: [],
  relations: [],
  delivery_settings: {
    allow_access: true,
    show_photos: true,
    show_banner: false,
    company_will_mail: false,
    show_extended_boilerplate: false,
    show_archives: true,
    show_alerts: true,
    delivery_method: 'standard',
  },
}

export const HKTDC: CompanyFull = {
  id: 128,
  name_en: 'Hong Kong Trade Development Council',
  name_zh_hans: '香港贸易发展局',
  name_zh_hant: '香港貿易發展局',
  name_ja: '香港貿易発展局',
  name_ko: null,
  status: 'active',
  logo_article_url: null,
  logo_top_url: null,
  url: 'https://www.hktdc.com',
  url_ja: null,
  blog: 'https://hkmb.hktdc.com',
  facebook: 'https://www.facebook.com/hktdc',
  twitter: 'https://twitter.com/hktdc',
  youtube: 'https://www.youtube.com/hktdc',
  linkedin: 'https://www.linkedin.com/company/hktdc',
  telegram: null,
  instagram: null,
  established: '1966',
  exchange_listed_date: null,
  employees: '1,000+',
  duns_number: null,
  otc: null,
  market_id: null,
  address_street: '38/F, Office Tower, Convention Plaza, 1 Harbour Road',
  address_district: 'Wan Chai',
  address_city: 'Hong Kong',
  address_country: 'Hong Kong SAR',
  telephone: '+852-1830-668',
  facsimile: '+852-2824-0249',
  company_email: 'hktdc@hktdc.org',
  key_person_1_name: 'Dr Peter K.N. Lam',
  key_person_1_title: 'Chairman',
  key_person_2_name: 'Margaret Fong',
  key_person_2_title: 'Executive Director',
  about_html: '<p>The Hong Kong Trade Development Council (HKTDC) is a statutory body established in 1966 to promote, assist and develop Hong Kong\'s trade. With over 50 offices globally, the HKTDC promotes Hong Kong as a two-way global investment and business hub.</p>',
  about_prosemirror: null,
  languages: ['EN'],
  secondary_languages: ['ZH-HANS', 'ZH-HANT'],
  created_at: '2016-11-01T00:00:00Z',
  updated_at: '2026-05-01T08:30:00Z',
  created_by: 1,
  updated_by: 3,
  updated_by_name: 'Krischan Balasbas',
  annual_report_url: null,
  annual_report_name: 'HKTDC_AR2026.pdf',
  annual_report_date: '2026-04-01',
  annual_report_size: '3.8 MB',
  portal_username: 'hktdc.hk.001',
  portal_password: '••••••••••••',
  contacts: [
    { id: 40, company_id: 128, name: 'Serena Cheung', position: 'Senior Manager, PR', email: 'serena.cheung@hktdc.org', phone: '+852-1830-668', fax: '+852-2824-0249', contact_type: 'freetext', email_format: 'html', notes: null, sort_order: 0, created_at: '2016-11-01T00:00:00Z', updated_at: '2016-11-01T00:00:00Z' },
  ],
  sectors: [
    { id: 50, company_id: 128, sector_id: 28,  sector_type: 'Business', sector_name: 'Trade Shows' },
    { id: 51, company_id: 128, sector_id: 234, sector_type: 'Business', sector_name: 'Local Biz' },
    { id: 52, company_id: 128, sector_id: 223, sector_type: 'Business', sector_name: 'ASEAN' },
  ],
  exchange_listings: [],
  wire_codes: [
    { id: 50, company_id: 128, wire_code_id: 101, wire_code: { id: 101, source: 'reuters',   code_type: 'Geographic', code: 'ASIA', name: 'Asia' } },
    { id: 51, company_id: 128, wire_code_id: 201, wire_code: { id: 201, source: 'bloomberg', code_type: 'Geographic', code: 'ASIA', name: 'Asia, Pacific Rim' } },
  ],
  rss_feeds: [
    { id: 10, company_id: 128, feed_name: 'HKTDC - Trade Shows', url: 'https://www.acnnewswire.com/rss/sector/28', sector_id: 28, sector_name: 'Trade Shows', status: 'active', created_at: '2016-11-01T00:00:00Z', updated_at: '2016-11-01T00:00:00Z' },
  ],
  wire_services: [],
  relations: [],
  delivery_settings: {
    allow_access: true,
    show_photos: true,
    show_banner: false,
    company_will_mail: false,
    show_extended_boilerplate: false,
    show_archives: true,
    show_alerts: true,
    delivery_method: 'standard',
  },
}

export const DATAVAULT_AI: CompanyFull = {
  id: 134,
  name_en: 'Datavault AI Inc.',
  name_zh_hans: null,
  name_zh_hant: null,
  name_ja: null,
  name_ko: null,
  status: 'active',
  logo_article_url: null,
  logo_top_url: null,
  url: 'https://ir.datavaultsite.com',
  url_ja: null,
  blog: null,
  facebook: null,
  twitter: null,
  youtube: null,
  linkedin: 'https://www.linkedin.com/company/datavault-ai',
  telegram: null,
  instagram: null,
  established: '2010',
  exchange_listed_date: '2025-02-01',
  employees: null,
  duns_number: null,
  otc: 'DVLT',
  market_id: null,
  address_street: '5765 SW Meadows Rd',
  address_district: null,
  address_city: 'Beaverton, Oregon',
  address_country: 'USA',
  telephone: null,
  facsimile: null,
  company_email: null,
  key_person_1_name: 'Nathaniel Bradley',
  key_person_1_title: 'Chief Executive Officer',
  key_person_2_name: 'Brett Moyer',
  key_person_2_title: 'Executive Chairman',
  about_html: '<p>Datavault AI Inc. (NASDAQ: DVLT) is a pioneering technology licensing company that owns a portfolio of patented, secure platforms designed to redefine how data is managed, valued, and monetized. The company operates two synergistic platforms: Data Science and Acoustic Science.</p>',
  about_prosemirror: null,
  languages: ['EN'],
  secondary_languages: [],
  created_at: '2025-03-01T00:00:00Z',
  updated_at: '2026-05-18T21:00:00Z',
  created_by: 3,
  updated_by: 3,
  updated_by_name: 'Krischan Balasbas',
  annual_report_url: null,
  annual_report_name: null,
  annual_report_date: null,
  annual_report_size: null,
  portal_username: 'dvlt.us.001',
  portal_password: '••••••••••••',
  contacts: [
    { id: 50, company_id: 134, name: 'Alan Wallace',  position: 'Head of Public Relations', email: 'alan.wallace@dvlt.ai',  phone: null, fax: null, contact_type: 'freetext', email_format: 'html', notes: null, sort_order: 0, created_at: '2025-03-01T00:00:00Z', updated_at: '2025-03-01T00:00:00Z' },
    { id: 51, company_id: 134, name: 'Edward Barger', position: 'VP, Investor Relations',   email: 'edward.barger@dvlt.ai', phone: null, fax: null, contact_type: 'freetext', email_format: 'html', notes: null, sort_order: 1, created_at: '2025-03-01T00:00:00Z', updated_at: '2025-03-01T00:00:00Z' },
  ],
  sectors: [
    { id: 60, company_id: 134, sector_id: 261, sector_type: 'Technology',     sector_name: 'Artificial Intel [AI]' },
    { id: 61, company_id: 134, sector_id: 214, sector_type: 'Cryptocurrency', sector_name: 'Blockchain Technology' },
    { id: 62, company_id: 134, sector_id: 257, sector_type: 'Finance',        sector_name: 'FinTech' },
  ],
  exchange_listings: [
    { id: 40, company_id: 134, exchange_id: 'XNAS', exchange_name: 'NASDAQ', ticker_code: 'DVLT', isin: null, sedol: null, cusip: null, created_at: '2025-03-01T00:00:00Z', updated_at: '2025-03-01T00:00:00Z' },
  ],
  wire_codes: [
    { id: 60, company_id: 134, wire_code_id: 106, wire_code: { id: 106, source: 'reuters',   code_type: 'General News',      code: 'NEWR', name: 'News Releases' } },
    { id: 61, company_id: 134, wire_code_id: 202, wire_code: { id: 202, source: 'bloomberg', code_type: 'Company',           code: 'COS',  name: 'Companies' } },
    { id: 62, company_id: 134, wire_code_id: 209, wire_code: { id: 209, source: 'bloomberg', code_type: 'Industrial Sector', code: 'TECH', name: 'Technology' } },
  ],
  rss_feeds: [],
  wire_services: [],
  relations: [],
  delivery_settings: {
    allow_access: true,
    show_photos: false,
    show_banner: false,
    company_will_mail: false,
    show_extended_boilerplate: false,
    show_archives: false,
    show_alerts: true,
    delivery_method: 'express',
  },
}

export const ACCENTURE: CompanyFull = {
  id: 142,
  name_en: 'Accenture plc',
  name_zh_hans: '埃森哲',
  name_zh_hant: '埃森哲',
  name_ja: 'アクセンチュア',
  name_ko: null,
  status: 'active',
  logo_article_url: null,
  logo_top_url: null,
  url: 'https://www.accenture.com',
  url_ja: null,
  blog: null,
  facebook: 'https://www.facebook.com/accenture',
  twitter: 'https://twitter.com/Accenture',
  youtube: 'https://www.youtube.com/accenture',
  linkedin: 'https://www.linkedin.com/company/accenture',
  telegram: null,
  instagram: null,
  established: '1989',
  exchange_listed_date: '2001-07-19',
  employees: '774,000+',
  duns_number: null,
  otc: null,
  market_id: null,
  address_street: '1 Grand Canal Square',
  address_district: 'Grand Canal Harbour',
  address_city: 'Dublin',
  address_country: 'Ireland',
  telephone: null,
  facsimile: null,
  company_email: null,
  key_person_1_name: 'Julie Sweet',
  key_person_1_title: 'Chair & CEO',
  key_person_2_name: null,
  key_person_2_title: null,
  about_html: '<p>Accenture is a leading global professional services company that helps the world\'s leading businesses, governments, and other organizations build their digital core, optimize their operations, and create growth. With revenues of US$65 billion and more than 774,000 people serving clients in more than 120 countries.</p>',
  about_prosemirror: null,
  languages: ['EN'],
  secondary_languages: [],
  created_at: '2017-05-08T00:00:00Z',
  updated_at: '2026-02-28T13:00:00Z',
  created_by: 1,
  updated_by: 1,
  updated_by_name: 'Bruce Porter',
  annual_report_url: null,
  annual_report_name: 'Accenture_AR2025.pdf',
  annual_report_date: '2025-11-30',
  annual_report_size: '8.2 MB',
  portal_username: 'accenture.ie.001',
  portal_password: '••••••••••••',
  contacts: [
    { id: 60, company_id: 142, name: 'Stacey Jones', position: 'Media Relations Asia Pacific', email: 'stacey.jones@accenture.com', phone: null, fax: null, contact_type: 'freetext', email_format: 'html', notes: 'Primary contact for APAC press releases', sort_order: 0, created_at: '2017-05-08T00:00:00Z', updated_at: '2017-05-08T00:00:00Z' },
  ],
  sectors: [
    { id: 70, company_id: 142, sector_id: 190, sector_type: 'Technology', sector_name: 'Enterprise IT' },
    { id: 71, company_id: 142, sector_id: 239, sector_type: 'Technology', sector_name: 'Digitalization' },
    { id: 72, company_id: 142, sector_id: 261, sector_type: 'Technology', sector_name: 'Artificial Intel [AI]' },
    { id: 73, company_id: 142, sector_id: 262, sector_type: 'Technology', sector_name: 'Automation [IoT]' },
  ],
  exchange_listings: [
    { id: 50, company_id: 142, exchange_id: 'XNYS', exchange_name: 'NYSE', ticker_code: 'ACN', isin: 'IE00B4BNMY34', sedol: 'B4BNMY3', cusip: null, created_at: '2017-05-08T00:00:00Z', updated_at: '2017-05-08T00:00:00Z' },
  ],
  wire_codes: [
    { id: 70, company_id: 142, wire_code_id: 101, wire_code: { id: 101, source: 'reuters',   code_type: 'Geographic',        code: 'ASIA', name: 'Asia' } },
    { id: 71, company_id: 142, wire_code_id: 106, wire_code: { id: 106, source: 'reuters',   code_type: 'General News',      code: 'NEWR', name: 'News Releases' } },
    { id: 72, company_id: 142, wire_code_id: 201, wire_code: { id: 201, source: 'bloomberg', code_type: 'Geographic',        code: 'ASIA', name: 'Asia, Pacific Rim' } },
    { id: 73, company_id: 142, wire_code_id: 209, wire_code: { id: 209, source: 'bloomberg', code_type: 'Industrial Sector', code: 'TECH', name: 'Technology' } },
    { id: 74, company_id: 142, wire_code_id: 202, wire_code: { id: 202, source: 'bloomberg', code_type: 'Company',           code: 'COS',  name: 'Companies' } },
  ],
  rss_feeds: [],
  wire_services: [],
  relations: [],
  delivery_settings: {
    allow_access: true,
    show_photos: true,
    show_banner: false,
    company_will_mail: false,
    show_extended_boilerplate: true,
    show_archives: true,
    show_alerts: false,
    delivery_method: 'express',
  },
}

export const IMPRO: CompanyFull = {
  id: 156,
  name_en: 'Impro Precision Industries Limited',
  name_zh_hans: '精工精密工业有限公司',
  name_zh_hant: '精工精密工業有限公司',
  name_ja: null,
  name_ko: null,
  status: 'active',
  logo_article_url: null,
  logo_top_url: null,
  url: 'https://www.improprecision.com',
  url_ja: null,
  blog: null,
  facebook: null,
  twitter: null,
  youtube: null,
  linkedin: 'https://www.linkedin.com/company/impro-precision-industries-limited',
  telegram: null,
  instagram: null,
  established: '1998',
  exchange_listed_date: '2019-06-28',
  employees: '7,897',
  duns_number: null,
  otc: null,
  market_id: null,
  address_street: '5/F, Tower 1, Kowloon Commerce Centre, 51 Kwai Cheong Road',
  address_district: 'Kwai Chung',
  address_city: 'Hong Kong',
  address_country: 'Hong Kong SAR',
  telephone: '+852-2480-5338',
  facsimile: null,
  company_email: 'ir@improprecision.com',
  key_person_1_name: 'Reb Lu',
  key_person_1_title: 'Founder & Chairman',
  key_person_2_name: null,
  key_person_2_title: null,
  about_html: '<p>Impro Precision Industries Limited is a world-leading manufacturer of high-precision, high-complexity, and mission-critical components. The company specializes in investment casting, precision machining, sand casting, and surface treatment, serving aerospace, automotive, medical, construction, and energy industries globally.</p>',
  about_prosemirror: null,
  languages: ['EN'],
  secondary_languages: ['ZH-HANT', 'ZH-HANS'],
  created_at: '2019-07-01T00:00:00Z',
  updated_at: '2026-04-15T09:00:00Z',
  created_by: 1,
  updated_by: 3,
  updated_by_name: 'Krischan Balasbas',
  annual_report_url: null,
  annual_report_name: 'Impro_AR2025.pdf',
  annual_report_date: '2026-03-28',
  annual_report_size: '3.1 MB',
  portal_username: 'impro.hk.001',
  portal_password: '••••••••••••',
  contacts: [
    { id: 70, company_id: 156, name: 'IR Team', position: 'Investor Relations', email: 'ir@improprecision.com', phone: '+852-2480-5338', fax: null, contact_type: 'freetext', email_format: 'html', notes: null, sort_order: 0, created_at: '2019-07-01T00:00:00Z', updated_at: '2019-07-01T00:00:00Z' },
  ],
  sectors: [
    { id: 80, company_id: 156, sector_id: 211, sector_type: 'Industry', sector_name: 'Aerospace & Defence' },
    { id: 81, company_id: 156, sector_id: 123, sector_type: 'Industry', sector_name: 'Automotive' },
    { id: 82, company_id: 156, sector_id: 91,  sector_type: 'Industry', sector_name: 'Manufacturing' },
    { id: 83, company_id: 156, sector_id: 33,  sector_type: 'Industry', sector_name: 'Construct, Engineering' },
  ],
  exchange_listings: [
    { id: 60, company_id: 156, exchange_id: 'XHKG', exchange_name: 'Hong Kong Stock Exchange', ticker_code: '1286', isin: 'HK0000398966', sedol: null, cusip: null, created_at: '2019-07-01T00:00:00Z', updated_at: '2019-07-01T00:00:00Z' },
  ],
  wire_codes: [
    { id: 80, company_id: 156, wire_code_id: 101, wire_code: { id: 101, source: 'reuters',   code_type: 'Geographic',        code: 'ASIA', name: 'Asia' } },
    { id: 81, company_id: 156, wire_code_id: 103, wire_code: { id: 103, source: 'reuters',   code_type: 'Industrial Sector', code: 'IND',  name: 'Industrial Equipment' } },
    { id: 82, company_id: 156, wire_code_id: 105, wire_code: { id: 105, source: 'reuters',   code_type: 'Industrial Sector', code: 'MAC',  name: 'Metal Goods and Engineering' } },
    { id: 83, company_id: 156, wire_code_id: 201, wire_code: { id: 201, source: 'bloomberg', code_type: 'Geographic',        code: 'ASIA', name: 'Asia, Pacific Rim' } },
    { id: 84, company_id: 156, wire_code_id: 214, wire_code: { id: 214, source: 'bloomberg', code_type: 'Industrial Sector', code: 'MACH', name: 'Machinery, Manufacturing' } },
  ],
  rss_feeds: [],
  wire_services: [],
  relations: [],
  delivery_settings: {
    allow_access: true,
    show_photos: true,
    show_banner: false,
    company_will_mail: false,
    show_extended_boilerplate: false,
    show_archives: true,
    show_alerts: true,
    delivery_method: 'standard',
  },
}

export const IQUANTI: CompanyFull = {
  id: 168,
  name_en: 'iQuanti, Inc.',
  name_zh_hans: null,
  name_zh_hant: null,
  name_ja: null,
  name_ko: null,
  status: 'active',
  logo_article_url: null,
  logo_top_url: null,
  url: 'https://www.iquanti.com',
  url_ja: null,
  blog: null,
  facebook: null,
  twitter: null,
  youtube: null,
  linkedin: 'https://www.linkedin.com/company/iquanti-inc',
  telegram: null,
  instagram: null,
  established: '2008',
  exchange_listed_date: null,
  employees: '500-1,000',
  duns_number: null,
  otc: null,
  market_id: null,
  address_street: '10 Exchange Place',
  address_district: null,
  address_city: 'Jersey City, New Jersey',
  address_country: 'USA',
  telephone: null,
  facsimile: null,
  company_email: 'press@iquanti.com',
  key_person_1_name: 'Arnab Sen',
  key_person_1_title: 'Chief Executive Officer',
  key_person_2_name: 'Vish Sastry Rachakonda',
  key_person_2_title: 'Founder & Executive Chairman',
  about_html: '<p>iQuanti is a data-driven digital marketing analytics and solutions company. Featured on the Inc. 5000 fastest growing companies list multiple times. iQuanti serves Fortune 500 clients including American Express, Avis, Allstate, and Wyndham, with offices in New York, London, Toronto, Mexico City, and Bangalore.</p>',
  about_prosemirror: null,
  languages: ['EN'],
  secondary_languages: [],
  created_at: '2021-06-15T00:00:00Z',
  updated_at: '2026-01-20T10:00:00Z',
  created_by: 2,
  updated_by: 2,
  updated_by_name: 'Shirley Chang',
  annual_report_url: null,
  annual_report_name: null,
  annual_report_date: null,
  annual_report_size: null,
  portal_username: 'iquanti.us.001',
  portal_password: '••••••••••••',
  contacts: [
    { id: 80, company_id: 168, name: 'Press Team', position: 'Media Relations', email: 'press@iquanti.com', phone: null, fax: null, contact_type: 'freetext', email_format: 'html', notes: null, sort_order: 0, created_at: '2021-06-15T00:00:00Z', updated_at: '2021-06-15T00:00:00Z' },
  ],
  sectors: [
    { id: 90, company_id: 168, sector_id: 261, sector_type: 'Technology', sector_name: 'Artificial Intel [AI]' },
    { id: 91, company_id: 168, sector_id: 239, sector_type: 'Technology', sector_name: 'Digitalization' },
    { id: 92, company_id: 168, sector_id: 215, sector_type: 'Finance',    sector_name: 'Banking & Insurance' },
    { id: 93, company_id: 168, sector_id: 257, sector_type: 'Finance',    sector_name: 'FinTech' },
  ],
  exchange_listings: [],
  wire_codes: [
    { id: 90, company_id: 168, wire_code_id: 106, wire_code: { id: 106, source: 'reuters',   code_type: 'General News', code: 'NEWR', name: 'News Releases' } },
    { id: 91, company_id: 168, wire_code_id: 202, wire_code: { id: 202, source: 'bloomberg', code_type: 'Company',     code: 'COS',  name: 'Companies' } },
  ],
  rss_feeds: [],
  wire_services: [],
  relations: [],
  delivery_settings: {
    allow_access: true,
    show_photos: false,
    show_banner: false,
    company_will_mail: false,
    show_extended_boilerplate: false,
    show_archives: false,
    show_alerts: true,
    delivery_method: 'standard',
  },
}

export const JCB: CompanyFull = {
  id: 199,
  name_en: 'JCB Co., Ltd.',
  name_zh_hans: '株式会社JCB',
  name_zh_hant: '株式會社JCB',
  name_ja: '株式会社ジェーシービー',
  name_ko: null,
  status: 'active',
  logo_article_url: null,
  logo_top_url: null,
  url: 'https://www.global.jcb/en',
  url_ja: 'https://www.jcb.co.jp',
  blog: null,
  facebook: null,
  twitter: 'https://twitter.com/JCBGlobal',
  youtube: null,
  linkedin: 'https://www.linkedin.com/company/jcb-co-ltd-',
  telegram: null,
  instagram: null,
  established: '1961',
  exchange_listed_date: null,
  employees: '3,500+',
  duns_number: null,
  otc: null,
  market_id: null,
  address_street: '5-1-22 Minami-Aoyama',
  address_district: 'Minato-ku',
  address_city: 'Tokyo',
  address_country: 'Japan',
  telephone: '+81-3-5778-8111',
  facsimile: null,
  company_email: null,
  key_person_1_name: 'Kimihisa Imada',
  key_person_1_title: 'President & CEO',
  key_person_2_name: null,
  key_person_2_title: null,
  about_html: '<p>JCB is a major global payment brand and card issuer based in Japan. Founded in 1961, JCB cards are accepted in over 190 countries and territories worldwide with over 160 million cardmembers globally. JCB is the only international payment brand originating from Japan.</p>',
  about_prosemirror: null,
  languages: ['EN'],
  secondary_languages: ['JA'],
  created_at: '2018-09-01T00:00:00Z',
  updated_at: '2026-03-05T14:00:00Z',
  created_by: 1,
  updated_by: 1,
  updated_by_name: 'Bruce Porter',
  annual_report_url: null,
  annual_report_name: 'JCB_AR2025.pdf',
  annual_report_date: '2025-09-30',
  annual_report_size: '2.9 MB',
  portal_username: 'jcb.jp.001',
  portal_password: '••••••••••••',
  contacts: [
    { id: 90, company_id: 199, name: 'JCB PR Team', position: 'Public Relations', email: 'pr@jcb.co.jp', phone: '+81-3-5778-8111', fax: null, contact_type: 'freetext', email_format: 'html', notes: null, sort_order: 0, created_at: '2018-09-01T00:00:00Z', updated_at: '2018-09-01T00:00:00Z' },
  ],
  sectors: [
    { id: 100, company_id: 199, sector_id: 94,  sector_type: 'Finance', sector_name: 'Cards & Payments' },
    { id: 101, company_id: 199, sector_id: 215, sector_type: 'Finance', sector_name: 'Banking & Insurance' },
    { id: 102, company_id: 199, sector_id: 257, sector_type: 'Finance', sector_name: 'FinTech' },
  ],
  exchange_listings: [],
  wire_codes: [
    { id: 100, company_id: 199, wire_code_id: 101, wire_code: { id: 101, source: 'reuters',   code_type: 'Geographic', code: 'ASIA',  name: 'Asia' } },
    { id: 101, company_id: 199, wire_code_id: 104, wire_code: { id: 104, source: 'reuters',   code_type: 'Geographic', code: 'JP',    name: 'Japan' } },
    { id: 102, company_id: 199, wire_code_id: 201, wire_code: { id: 201, source: 'bloomberg', code_type: 'Geographic', code: 'ASIA',  name: 'Asia, Pacific Rim' } },
    { id: 103, company_id: 199, wire_code_id: 205, wire_code: { id: 205, source: 'bloomberg', code_type: 'Geographic', code: 'JAPAN', name: 'Japan' } },
    { id: 104, company_id: 199, wire_code_id: 211, wire_code: { id: 211, source: 'bloomberg', code_type: 'Industrial Sector', code: 'FIN', name: 'Finance' } },
  ],
  rss_feeds: [],
  wire_services: [],
  relations: [],
  delivery_settings: {
    allow_access: true,
    show_photos: true,
    show_banner: false,
    company_will_mail: false,
    show_extended_boilerplate: false,
    show_archives: true,
    show_alerts: true,
    delivery_method: 'standard',
  },
}

export const ALL_SEED_COMPANIES: CompanyFull[] = [
  SEED_COMPANY,   // MHI          id: 82
  TOYOTA,         // Toyota        id: 91
  FUJITSU,        // Fujitsu       id: 103
  HONDA,          // Honda         id: 117
  HKTDC,          // HKTDC         id: 128
  DATAVAULT_AI,   // Datavault AI  id: 134
  ACCENTURE,      // Accenture     id: 142
  IMPRO,          // Impro         id: 156
  IQUANTI,        // iQuanti       id: 168
  JCB,            // JCB           id: 199
]

export function seedLocalStorage(): void {
  ALL_SEED_COMPANIES.forEach(company => {
    localStorage.setItem(`acn_company_${company.id}`, JSON.stringify(company))
  })
  ALL_SEED_ARTICLES.forEach(article => {
    localStorage.setItem(`acn_article_${article.id}`, JSON.stringify(article))
  })
  console.info(
    `[ACN seed] Seeded ${ALL_SEED_COMPANIES.length} companies and ${ALL_SEED_ARTICLES.length} press releases`
  )
}

export function clearSeed(): void {
  Object.keys(localStorage)
    .filter(k => k.startsWith('acn_'))
    .forEach(k => localStorage.removeItem(k))
  console.info('[ACN seed] Cleared all acn_* localStorage keys')
}
